"""Speaker Diarization Provider Interface.

Defines the contract for future real-time (Diart) or offline (pyannote.audio)
speaker diarization backends without coupling audio dependencies into the NLP module.
"""

from abc import ABC, abstractmethod
from typing import List, Optional
from pydantic import BaseModel, ConfigDict


class SpeakerSegment(BaseModel):
    """Timestamped speaker turn generated by a diarization engine."""
    speaker: str
    start: float
    end: float

    model_config = ConfigDict(extra="ignore")


class DiarizationProvider(ABC):
    """Abstract base class for audio diarization providers."""

    @abstractmethod
    def diarize(self, audio_path: str) -> List[SpeakerSegment]:
        """Perform speaker diarization on an audio file or stream buffer.
        
        Args:
            audio_path: Path to target audio file or stream identifier.
            
        Returns:
            List of detected SpeakerSegments.
        """
        raise NotImplementedError("Diarization backends (Diart / pyannote) are plugged in at the audio layer.")
